sudo: false
language: go

services:
  - docker

go:
- 1.8.1

before_install:
- docker build --no-cache -t elm-env ui/.

script:
- make
- docker run --rm -t -v "$(pwd):/app" -w /app/ui/app elm-env elm-format --validate src/

- docker run --rm -t -v "$(pwd):/app" -w /app/ui/app elm-env make script.js
- docker run --rm -t -v "$(pwd):/usr/src/app" -w /usr/src/app golang make assets
- git diff --exit-code

- docker run --rm -t -v "$(pwd):/app" -w /app/ui/app elm-env make test
